services:
  mysql_db:
    image: mysql:8.0
    container_name: central_mysql
    environment:
      MYSQL_DATABASE: central_esterilizacion
      MYSQL_ROOT_PASSWORD: admin_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # No pierdes datos al apagar Docker